config/routes.rb
Rails.application.routes.draw do
  devise_for :trainers
  root to: "home#index"

 ## Part 2: Create a new route in your routes file that will call the function you just wrote. Name the path capture as its prefix. Set the URI pattern to be "capture".

  patch '/capture', to: 'pokemons#capture', as: 'capture'

  ## Part 3: You should redirect back to the trainer's profile page at the end of the damage method. Hint: run rake routes to see what path you need.

  patch '/damaga', to: 'pokemons#damage', as: 'damage'

  ##  Part 5: create new Pokemon.
  post 'create', to: 'pokemons#create', as: 'create'

  get 'new', to: 'pokemons#new', as: 'new'

  resources :trainers
  resources :pokemons

end

app/models/add_health_to_pokemon.rb
class AddHealthToPokemon < ApplicationRecord
end

app/models/pokemon.rb
class Pokemon < ApplicationRecord
	belongs_to :trainer, optional:true
	validates :name, presence:true, uniqueness:true
end

app/models/trainer.rb
class Trainer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :pokemons
end

app/controllers/pokemons_controller.rb
class PokemonsController < ApplicationController
	def capture
		@pokemon = Pokemon.find(params[:id])
		@pokemon.trainer = current_trainer
		@pokemon.save
		redirect_to '/'
	end


	def damage
		@pokemon = Pokemon.where(id: params[:id]).first
		@pokemon.health -= 10
		if @pokemon.health <= 0
			flash[:destroy] = "Your Pokemon is dead!"
			@pokemon.destroy
		else
			@pokemon.save
		end
		redirect_to trainer_path(id: @pokemon.trainer)

	end

	def new
		@pokemon = Pokemon.new
	end

	def create
		@pokemon = Pokemon.new(params.require(:pokemon).permit(:name))
		@pokemon.level = 1
		@pokemon.health = 100
		@pokemon.trainer = current_trainer
		if @pokemon.save
			redirect_to trainer_path(id: @pokemon.trainer)
		else
			redirect_to new_pokemon_path
		    flash[:error] = @pokemon.errors.full_messages.to_sentence
		end
	end

end

app/helpers/pokemon_helper.rb
module PokemonHelper
end

app/helpers/pokemons_helper.rb
module PokemonsHelper
end

app/views/home/index.html.erb
<h3>Welcome to PokePortal</h3>
<p><%= link_to 'Trainers:', trainers_path %> <%= Trainer.count %> registered</p>

<% if @pokemon and current_trainer %>
  <p> A wild <%= @pokemon.name %> has appeared!</p>
  <!-- REPLACE THIS LINE BELOW -->
  <%= button_to "Throw a Pokeball!", capture_path(id: @pokemon), :class => "button medium", :method => :patch %>
<% end %>

app/views/pokemons/new.html.erb
<%= simple_form_for :pokemon, :url => create_path do |f| %>
  <%= f.input :name, label: "Pokemon's name: ", error: 'You must name your Pokemon!!!' %>
  <%= f.button :submit, 'Create New Pokemon' %>
<% end %>

app/views/trainers/show.html.erb
<h3>Trainer</h3>
<p>Name: <%= @trainer.name if @trainer.name %></p>
<p>Email: <%= @trainer.email if @trainer.email %></p>

<p> Trainer's Pokemons name, levels, health </p>
<% @trainer.pokemons.each do |pokemon| %>
<li><%= pokemon.name %> <%= pokemon.level %> <%= pokemon.health %>

<%= button_to "Damage!", damage_path(id: pokemon), :class => "button medium", :method => :patch %>

 </li>

<% end %>

<p> Create Your Own Pokemon </p>
<%= button_to "Create New Pokemon", new_pokemon_path, :class => "button large", :method => :get %>